{{- if .Values.secretAccess.readAll }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "pact.fullname" . }}-secret-reader-all
  labels:
    {{- include "pact.labels" . | nindent 4 }}
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["get"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "pact.fullname" . }}-secret-reader-all
  labels:
    {{- include "pact.labels" . | nindent 4 }}
subjects:
  - kind: ServiceAccount
    name: {{ include "pact.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "pact.fullname" . }}-secret-reader-all
{{- end }}
